/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Cleiton
 */
public class TelaUrna extends javax.swing.JFrame {

    /**
     * Creates new form tel
     */
    String matricula = "";

    public TelaUrna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Teclado = new javax.swing.JPanel();
        jP_bt1 = new javax.swing.JPanel();
        bt1 = new javax.swing.JLabel();
        jP_bt2 = new javax.swing.JPanel();
        bt2 = new javax.swing.JLabel();
        jP_bt3 = new javax.swing.JPanel();
        bt3 = new javax.swing.JLabel();
        jP_bt4 = new javax.swing.JPanel();
        bt4 = new javax.swing.JLabel();
        jP_bt5 = new javax.swing.JPanel();
        bt5 = new javax.swing.JLabel();
        jP_bt6 = new javax.swing.JPanel();
        bt6 = new javax.swing.JLabel();
        jP_bt7 = new javax.swing.JPanel();
        bt7 = new javax.swing.JLabel();
        jP_bt8 = new javax.swing.JPanel();
        bt8 = new javax.swing.JLabel();
        jP_bt9 = new javax.swing.JPanel();
        bt9 = new javax.swing.JLabel();
        jP_bt0 = new javax.swing.JPanel();
        bt0 = new javax.swing.JLabel();
        jP_btbranco = new javax.swing.JPanel();
        btBranco = new javax.swing.JLabel();
        jP_btCorrige = new javax.swing.JPanel();
        btCorrige = new javax.swing.JLabel();
        jP_btConfirma = new javax.swing.JPanel();
        btConfirma = new javax.swing.JLabel();
        Tela = new javax.swing.JPanel();
        jPFoto = new javax.swing.JPanel();
        jLFoto = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        Teclado.setBackground(new java.awt.Color(204, 204, 255));

        jP_bt1.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt1.setPreferredSize(new java.awt.Dimension(200, 200));

        bt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt1.setForeground(new java.awt.Color(102, 102, 102));
        bt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt1.setText("1");
        bt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt1Layout = new javax.swing.GroupLayout(jP_bt1);
        jP_bt1.setLayout(jP_bt1Layout);
        jP_bt1Layout.setHorizontalGroup(
            jP_bt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt1Layout.setVerticalGroup(
            jP_bt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_bt2.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt2.setPreferredSize(new java.awt.Dimension(200, 200));

        bt2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt2.setForeground(new java.awt.Color(102, 102, 102));
        bt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt2.setText("2");
        bt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt2Layout = new javax.swing.GroupLayout(jP_bt2);
        jP_bt2.setLayout(jP_bt2Layout);
        jP_bt2Layout.setHorizontalGroup(
            jP_bt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt2Layout.setVerticalGroup(
            jP_bt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_bt2Layout.createSequentialGroup()
                .addComponent(bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jP_bt3.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt3.setPreferredSize(new java.awt.Dimension(200, 200));

        bt3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt3.setForeground(new java.awt.Color(102, 102, 102));
        bt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt3.setText("3");
        bt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt3Layout = new javax.swing.GroupLayout(jP_bt3);
        jP_bt3.setLayout(jP_bt3Layout);
        jP_bt3Layout.setHorizontalGroup(
            jP_bt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt3, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt3Layout.setVerticalGroup(
            jP_bt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_bt4.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt4.setPreferredSize(new java.awt.Dimension(200, 200));

        bt4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt4.setForeground(new java.awt.Color(102, 102, 102));
        bt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt4.setText("4");
        bt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt4Layout = new javax.swing.GroupLayout(jP_bt4);
        jP_bt4.setLayout(jP_bt4Layout);
        jP_bt4Layout.setHorizontalGroup(
            jP_bt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt4, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt4Layout.setVerticalGroup(
            jP_bt4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_bt5.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt5.setPreferredSize(new java.awt.Dimension(200, 200));

        bt5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt5.setForeground(new java.awt.Color(102, 102, 102));
        bt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt5.setText("5");
        bt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt5Layout = new javax.swing.GroupLayout(jP_bt5);
        jP_bt5.setLayout(jP_bt5Layout);
        jP_bt5Layout.setHorizontalGroup(
            jP_bt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt5, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt5Layout.setVerticalGroup(
            jP_bt5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_bt6.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt6.setPreferredSize(new java.awt.Dimension(200, 200));

        bt6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt6.setForeground(new java.awt.Color(102, 102, 102));
        bt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt6.setText("6");
        bt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt6Layout = new javax.swing.GroupLayout(jP_bt6);
        jP_bt6.setLayout(jP_bt6Layout);
        jP_bt6Layout.setHorizontalGroup(
            jP_bt6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt6, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt6Layout.setVerticalGroup(
            jP_bt6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_bt7.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt7.setPreferredSize(new java.awt.Dimension(200, 200));

        bt7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt7.setForeground(new java.awt.Color(102, 102, 102));
        bt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt7.setText("7");
        bt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt7Layout = new javax.swing.GroupLayout(jP_bt7);
        jP_bt7.setLayout(jP_bt7Layout);
        jP_bt7Layout.setHorizontalGroup(
            jP_bt7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt7, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt7Layout.setVerticalGroup(
            jP_bt7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_bt8.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt8.setPreferredSize(new java.awt.Dimension(200, 200));

        bt8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt8.setForeground(new java.awt.Color(102, 102, 102));
        bt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt8.setText("8");
        bt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt8Layout = new javax.swing.GroupLayout(jP_bt8);
        jP_bt8.setLayout(jP_bt8Layout);
        jP_bt8Layout.setHorizontalGroup(
            jP_bt8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt8, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt8Layout.setVerticalGroup(
            jP_bt8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_bt9.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt9.setPreferredSize(new java.awt.Dimension(200, 200));

        bt9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt9.setForeground(new java.awt.Color(102, 102, 102));
        bt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt9.setText("9");
        bt9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt9Layout = new javax.swing.GroupLayout(jP_bt9);
        jP_bt9.setLayout(jP_bt9Layout);
        jP_bt9Layout.setHorizontalGroup(
            jP_bt9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt9, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt9Layout.setVerticalGroup(
            jP_bt9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_bt0.setBackground(new java.awt.Color(204, 255, 255));
        jP_bt0.setPreferredSize(new java.awt.Dimension(200, 200));

        bt0.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bt0.setForeground(new java.awt.Color(102, 102, 102));
        bt0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt0.setText("0");
        bt0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bt0MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_bt0Layout = new javax.swing.GroupLayout(jP_bt0);
        jP_bt0.setLayout(jP_bt0Layout);
        jP_bt0Layout.setHorizontalGroup(
            jP_bt0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_bt0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bt0, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_bt0Layout.setVerticalGroup(
            jP_bt0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_btbranco.setPreferredSize(new java.awt.Dimension(200, 200));

        btBranco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btBranco.setForeground(new java.awt.Color(102, 102, 102));
        btBranco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btBranco.setText("BRANCO");
        btBranco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBrancoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_btbrancoLayout = new javax.swing.GroupLayout(jP_btbranco);
        jP_btbranco.setLayout(jP_btbrancoLayout);
        jP_btbrancoLayout.setHorizontalGroup(
            jP_btbrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_btbrancoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btBranco, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_btbrancoLayout.setVerticalGroup(
            jP_btbrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btBranco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_btCorrige.setPreferredSize(new java.awt.Dimension(200, 200));

        btCorrige.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCorrige.setForeground(new java.awt.Color(102, 102, 102));
        btCorrige.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btCorrige.setText("CORRIGE");
        btCorrige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btCorrigeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_btCorrigeLayout = new javax.swing.GroupLayout(jP_btCorrige);
        jP_btCorrige.setLayout(jP_btCorrigeLayout);
        jP_btCorrigeLayout.setHorizontalGroup(
            jP_btCorrigeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_btCorrigeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCorrige, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_btCorrigeLayout.setVerticalGroup(
            jP_btCorrigeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btCorrige, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jP_btConfirma.setPreferredSize(new java.awt.Dimension(200, 200));

        btConfirma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btConfirma.setForeground(new java.awt.Color(102, 102, 102));
        btConfirma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btConfirma.setText("CONFIRMA");
        btConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btConfirmaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jP_btConfirmaLayout = new javax.swing.GroupLayout(jP_btConfirma);
        jP_btConfirma.setLayout(jP_btConfirmaLayout);
        jP_btConfirmaLayout.setHorizontalGroup(
            jP_btConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_btConfirmaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
        );
        jP_btConfirmaLayout.setVerticalGroup(
            jP_btConfirmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btConfirma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TecladoLayout = new javax.swing.GroupLayout(Teclado);
        Teclado.setLayout(TecladoLayout);
        TecladoLayout.setHorizontalGroup(
            TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TecladoLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_btbranco, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_btCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 92, Short.MAX_VALUE)
                .addGroup(TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_btConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        TecladoLayout.setVerticalGroup(
            TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TecladoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_bt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_bt4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jP_bt7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jP_bt9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jP_bt0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jP_btCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jP_btbranco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jP_btConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        Tela.setBackground(new java.awt.Color(255, 255, 255));

        jLFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLFoto.setText("Foto");

        javax.swing.GroupLayout jPFotoLayout = new javax.swing.GroupLayout(jPFoto);
        jPFoto.setLayout(jPFotoLayout);
        jPFotoLayout.setHorizontalGroup(
            jPFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPFotoLayout.setVerticalGroup(
            jPFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jLabelMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMatricula.setText("Matricula");

        jLabelNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNome.setText("Nome");

        jLabelIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIdade.setText("Idade");

        jTextFieldIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldIdade.setEnabled(false);

        jTextFieldMatricula.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldMatricula.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldMatricula.setEnabled(false);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldNome.setEnabled(false);

        javax.swing.GroupLayout TelaLayout = new javax.swing.GroupLayout(Tela);
        Tela.setLayout(TelaLayout);
        TelaLayout.setHorizontalGroup(
            TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaLayout.createSequentialGroup()
                        .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelMatricula)
                            .addComponent(jLabelIdade))
                        .addGap(18, 18, 18)
                        .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TelaLayout.createSequentialGroup()
                        .addComponent(jPFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))))
        );
        TelaLayout.setVerticalGroup(
            TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TelaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMatricula))
                .addGap(86, 86, 86)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome))
                .addGap(84, 84, 84)
                .addGroup(TelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIdade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Teclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Teclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizaMatricula() {
        jTextFieldMatricula.setText(matricula);
    }

    private void bt1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt1MousePressed
        matricula = matricula + "1";
        atualizaMatricula();
    }//GEN-LAST:event_bt1MousePressed

    private void bt2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt2MousePressed
        matricula = matricula + "2";
        atualizaMatricula();
    }//GEN-LAST:event_bt2MousePressed

    private void bt3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt3MousePressed
        matricula = matricula + "3";
        atualizaMatricula();
    }//GEN-LAST:event_bt3MousePressed

    private void bt4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt4MousePressed
        matricula = matricula + "4";
        atualizaMatricula();
    }//GEN-LAST:event_bt4MousePressed

    private void bt5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt5MousePressed
        matricula = matricula + "5";
        atualizaMatricula();
    }//GEN-LAST:event_bt5MousePressed

    private void bt6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt6MousePressed
        matricula = matricula + "6";
        atualizaMatricula();
    }//GEN-LAST:event_bt6MousePressed

    private void bt7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt7MousePressed
        matricula = matricula + "7";
        atualizaMatricula();
    }//GEN-LAST:event_bt7MousePressed

    private void bt8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt8MousePressed
        matricula = matricula + "8";
        atualizaMatricula();
    }//GEN-LAST:event_bt8MousePressed

    private void bt9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt9MousePressed
        matricula = matricula + "9";
        atualizaMatricula();
    }//GEN-LAST:event_bt9MousePressed

    private void bt0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt0MousePressed
        matricula = matricula + "0";
        atualizaMatricula();
    }//GEN-LAST:event_bt0MousePressed

    private void btBrancoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBrancoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBrancoMousePressed

    private void btCorrigeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCorrigeMousePressed
        matricula = "";
        atualizaMatricula();
    }//GEN-LAST:event_btCorrigeMousePressed

    private void btConfirmaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btConfirmaMousePressed
        System.out.println("Mat1 - " + matricula);
    }//GEN-LAST:event_btConfirmaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUrna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUrna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Teclado;
    private javax.swing.JPanel Tela;
    private javax.swing.JLabel bt0;
    private javax.swing.JLabel bt1;
    private javax.swing.JLabel bt2;
    private javax.swing.JLabel bt3;
    private javax.swing.JLabel bt4;
    private javax.swing.JLabel bt5;
    private javax.swing.JLabel bt6;
    private javax.swing.JLabel bt7;
    private javax.swing.JLabel bt8;
    private javax.swing.JLabel bt9;
    private javax.swing.JLabel btBranco;
    private javax.swing.JLabel btConfirma;
    private javax.swing.JLabel btCorrige;
    private javax.swing.JLabel jLFoto;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPFoto;
    private javax.swing.JPanel jP_bt0;
    private javax.swing.JPanel jP_bt1;
    private javax.swing.JPanel jP_bt2;
    private javax.swing.JPanel jP_bt3;
    private javax.swing.JPanel jP_bt4;
    private javax.swing.JPanel jP_bt5;
    private javax.swing.JPanel jP_bt6;
    private javax.swing.JPanel jP_bt7;
    private javax.swing.JPanel jP_bt8;
    private javax.swing.JPanel jP_bt9;
    private javax.swing.JPanel jP_btConfirma;
    private javax.swing.JPanel jP_btCorrige;
    private javax.swing.JPanel jP_btbranco;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
